name: Github Workflow Example
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: NPM CI
        run: npm ci
      - name: NPM Install
        run: npm install
      - name: NPM Build
        run: npm run build
      - name: Publish JS filename
        run: find dist/assets/*.js -type f -execdir echo '{}' ';'
      - name: Generate Artifcats
        uses: actions/upload-artifact@v3
        with:
            name: dist-files
            path: dist

  info:
    runs-on: ubuntu-latest
    steps:
    - name: Print Issue Metadata
      run: |
        echo "${{ toJson(github.event) }}"