name: Issues Workflow
on:
  issues:
    types: [opened, edited, closed]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Github Issues Information
        run: echo "${{ github.event.issue.body }}"
  
